language: python

python:
  - "2.7"
  - "3.3"

# command to install dependencies
install:
  - "pip install cython==0.20.2"
  - "pip install numpy"
  - "pip install tables"

script: 
  - python numper.py
  - python jickle.py
