sudo: false

language: python

python:
  #- "2.6"
  - "2.7"
  #- "3.3"

# command to install dependencies
install:
  - env
  - git clone https://github.com/NeuroML/pyNeuroML.git
  - cd pyNeuroML
  - pip install . -r requirements.txt
    
script:
    - pynml -h
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    - omv install jLEMS
    - omv install NEURON
    - omv list-engines
    - ls -alt /home/travis/neuron/nrn/x86_64/bin
    - /home/travis/neuron/nrn/x86_64/bin/nrnivmodl
    
  #- sudo apt-get install -qq libhdf5-serial-dev 
  #- "pip install cython==0.20.2"
  #- "pip install numpy"
  #- "pip install numexpr"
  #- "pip install tables"
  #- "pip install jsonpickle"

#script: 
#  - python numper.py
#  - python jickle.py
