language: python

python:
  - "2.7"
  - "3.3"

# command to install dependencies
install:
  - sudo apt-get install -qq libhdf5-serial-dev 
  - "pip install cython"
  - "pip install numpy"
  - "pip install numexpr"
  - "pip install tables"

script: 
  - python numper.py
